import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/app/firebase-context';
import Navbar from "@/app/ui/navbar";
import Footer from "@/app/ui/footer";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
        ><AuthProvider>
            <div className="flex">
                <Navbar/>
                <Footer/>

            </div>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
